title: Vishal Bhosale
logo: "VB_Photo.jpg?raw:true"
description:
QA Analyst
<br>
<a href="mailto:vishalbhosale597@gmail.com">vishalbhosale597@gmail.com</a>
<br>
<a href="https://www.linkedin.com/in/vishal-bhosale/">LinkedIn Profie<a/>
theme: jekyll-theme-minimal
